[package]
name = "auraxis_macros"
description = "Macros for working with the auraxis crate"
license = "MIT"
version = "0.1.0"
edition = "2021"

[lib]
name = "auraxis_macros"
proc-macro = true

[dependencies]
darling = "0.14.2"
quote = "1.0.21"
syn = "1.0.103"
