[advisories]
# RUSTSEC-2020-0071 is a time crate vulnerability. The only dependency that uses it is chrono, which does not use the vulnerable code. Chrono 0.5 should fix this issue, but it is not out yet.
ignore = ["RUSTSEC-2020-0071"]
