on:
  push:
    # branches:
    #   - master
    paths:
      - '**.rs'
      - '**.toml'
      - '**.md'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/cargo-doc-pages.yaml'

name: Publish cargo doc to pages

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
      - name: Build cargo doc
        run: cargo doc --release --all-features --no-deps
      - name: Create index.html
        run: echo '<meta http-equiv=refresh content=0;url=auraxis/index.html>' > target/doc/index.html
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc

  publish-docs:
    name: Publish documentation
    needs: build-docs
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        id: deployment


